Provide a proper implementation of the V2 API for Genera and fix a race condition in locking
sionescu/bordeaux-threads pull request #90
Opened 2021-02-25 03:04 UTC by gmpalter

Move QUEUE from atomics.lisp to impl-condition-variables-semaphores.lisp, which is
the only file which uses QUEUE, as the Genera implementation does not define %WITH-LOCK.
(impl-condition-variables-semaphores.lisp is only used by CCL.)

On Genera, fix the calls to PROCESS:PROCESS-KILL in DESTROY-THREAD --
the WITHOUT-ABORTS argument is an optional not a keyword argument.

Fix a race condition in locking and unlocking --
Assume two processes, A and B, and a lock. Process A locks the lock. Process B then tries
to lock the lock and blocks until A unlocks it. As currently written, when process A
unlocks the lock, Genera might switch to process B before process A can reset the lock's
internal BT state to indicate it no longer has the lock. Process B then updates the
internal state to indicate it has the lock which Genera has given it. Process A then
runs and reset the lock's internal state. When process B tries to unlock the lock,
it will crash because it passes an invalid value to Genera's process:unlock.

The fix is to make all lock/unlock operations in BT atomic w.r.t. locking/unlocking
the Genera lock and updating the internal state.

2021-02-25 03:34 UTC, sionescu requested changes

2021-02-25 03:34 UTC, sionescu commented on apiv2/api-threads.lisp
> +    ;; Genera doesn't yet implement COPY-PPRINT-DISPATCH
If Genera doesn't support this then exclude the whole binding.

2021-02-25 03:34 UTC, sionescu commented on apiv2/api-threads.lisp
> +					    (funcall function))))))
Please don't use tabs for indentation.

2021-02-25 03:34 UTC, sionescu commented on apiv2/atomics.lisp
> +  #+genera `(sys:store-conditional (scl:locf ,place) ,old ,new)
Place all the reader conditionals in alphabetical order.

2021-02-25 17:35 UTC, gmpalter commented
I have pushed a change to address your comments above. I then squashed that change into the original so there is only 1 commit on this branch. (I also tweaked the commit comment a bit.)

2021-02-28 05:29 UTC, sionescu commented
Thanks, merged.

2021-02-28 05:29 UTC, closed without merging